import csv
import shutil

import dxpy

from pathlib import Path
from typing import Optional

from general_utilities.import_utils.genetics_loader import GeneticsLoader
from general_utilities.import_utils.import_lib import ingest_wes_bgen, ingest_tarballs
from general_utilities.import_utils.module_loader.ingest_data import IngestData
from burden.burden_association_pack import BurdenAssociationPack, BurdenProgramArgs


class BurdenIngestData(IngestData):

    def __init__(self, parsed_options: BurdenProgramArgs):
        super().__init__(parsed_options)

        # Put additional options/covariate processing required by this specific package here
        if len(self.get_association_pack().pheno_names) > 1:
            raise dxpy.AppError('The burden module currently only allows for running one phenotype at a time!')

        is_snp_tar, is_gene_tar, tarball_prefixes, tarball_chunks = ingest_tarballs(parsed_options.association_tarballs)
        if is_snp_tar or is_gene_tar:
            raise dxpy.AppError('The burden module is not compatible with SNP or GENE masks!')

        # Ingest WES filtered and annotated bgen
        bgen_dict = ingest_wes_bgen(parsed_options.bgen_index)

        GeneticsLoader(parsed_options.array_bed_file,
                       parsed_options.array_fam_file,
                       parsed_options.array_bim_file,
                       sample_files=[],
                       cmd_executor=self._association_pack.cmd_executor,
                       low_mac_list=parsed_options.low_MAC_list,
                       sparse_grm=parsed_options.sparse_grm,
                       sparse_grm_sample=parsed_options.sparse_grm_sample)

        regenie_snps_file = self._process_regenie_snps(parsed_options.regenie_smaller_snps)

        # Put additional covariate processing specific to this module here
        self.set_association_pack(BurdenAssociationPack(self.get_association_pack(),
                                                        tarball_prefixes, bgen_dict,
                                                        parsed_options.run_marker_tests,
                                                        parsed_options.bolt_non_infinite, regenie_snps_file,
                                                        tarball_chunks))

    # Need to grab the tarball file for associations...
    # This was generated by the applet mrcepid-collapsevariants
    # Ingest the list file into this AWS instance

    @staticmethod
    def _process_regenie_snps(snp_qc_file: dxpy.DXFile, dna_nexus_run: bool = False) -> Optional[Path]:

        if snp_qc_file is None:
            return None
        else:
            if dna_nexus_run:
                dxpy.download_dxfile(snp_qc_file.get_id(), 'genetics/ukb_snp_qc.txt')
            else:
                shutil.copy(Path(snp_qc_file), 'genetics/ukb_snp_qc.txt')
            with Path('genetics/ukb_snp_qc.txt').open('r') as snp_qc_reader,\
                    Path('genetics/rel_snps.txt').open('w') as rel_snps_writer:
                snp_qc_csv = csv.DictReader(snp_qc_reader, delimiter=" ")
                for snp in snp_qc_csv:
                    if snp['in_Relatedness'] == '1':
                        rel_snps_writer.write(f'{snp["rs_id"]}\n')
                snp_qc_reader.close()
                rel_snps_writer.close()

            return Path('genetics/rel_snps.txt')
